CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'CsE344RaNdOm$Key';

CREATE DATABASE SCOPED
CREDENTIAL QueryCredential
WITH IDENTITY = 'reader2020', SECRET = '20wiUWcse()';

CREATE EXTERNAL DATA SOURCE CSE344_EXTERNAL
WITH
( TYPE = RDBMS,
  LOCATION='khangishandsome.database.windows.net',
  DATABASE_NAME = 'cse344_readonly',
  CREDENTIAL = QueryCredential
);

DROP EXTERNAL TABLE  Flights;
DROP EXTERNAL TABLE  Carriers;
DROP EXTERNAL TABLE  Weekdays;
DROP EXTERNAL TABLE  Months;
DROP  TABLE  users;
DROP  TABLE  reservations;
DROP  TABLE  ID;
DROP  TABLE  capacity;